### ISSUE TITLE
theme (light and dark) toggling is not present

### ISSUE THREAD

**Issue by mrgulrez** [arakoodev/doc#9] opened 2023-05-29 19:40 UTC
### Is your feature request related to a problem? Please describe.

Light and Dark Theme Toggling" feature in a webpage offers improved user experience, accessibility, reduced eye fatigue, energy efficiency, aesthetic appeal, personalization, and compatibility with other apps. By providing this feature, web developers can cater to various user preferences and create a more inclusive and engaging browsing experience.

### Describe the solution you'd like

I want to add theme toggle in navbar section

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Charan2437** [comment] 2023-05-30 03:11
hello sir, could you assign this issue to me ?

**Comment by sandys** [comment] 2023-06-01 06:01
@mrgulrez this is a good suggestion, however to follow brand guidelines, we will not allow toggle. we want people to see the page as intended.

however, this was a FANTASTIC idea in general and we would love for you to come up with more ideas that we can implement in the site. 

closing with thanks.

**Closed by sandys** 2023-06-01 06:01 UTC
Labels: enhancement
