### ISSUE TITLE
Adding proper padding and margin to the page 

### ISSUE THREAD

**Issue by AmanSingh6574** [arakoodev/doc#29] opened 2023-06-19 17:23 UTC
### Is your feature request related to a problem? Please describe.

![image](https://github.com/arakoodev/doc/assets/113782984/30b12c07-8123-4ceb-801f-1b42adf5253f)

### Describe the solution you'd like

Adding proper padding and margin to the page 

### Additional context

pls assign me this issue under GSSOC'23
@sandys 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sandys** [comment] 2023-06-19 17:36
duplicate of https://github.com/arakoodev/doc/issues/25 
closing issue

**Closed by sandys** 2023-06-19 17:36 UTC
Labels: duplicate, enhancement
